# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dpuser',
            name='password',
            field=models.CharField(default=b'happy', max_length=50),
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject.DPUser'),
        ),
    ]
